name: Development CI-CD workflow

on:
  push:
    branches:
      - development

jobs:
  check-node-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - runs: node --version
